### ISSUE TITLE
VertexHelper Issues

### ISSUE THREAD

**Issue by codestry** [jfahrenkrug/VertexHelper#6]
I am having a problem running Vertex Helper. Any time I run it i get a warning which says "the run destination My Mac 64-bit is not valid for running the scheme 'vertexhelper'. the scheme 'VertexHelper' contains no buildables that can be built for the SDKs supported by the run destination My Mac 64-bit . Make sure your targets all specify SDKs that can be supported by this version of xcode ".  I am using xcode 4.1 and I can't change the run destination. Please help.

**Comment by Ermiasmarino** [comment]
Hi Yohannes, I hope you are doing great. Yohannes, I am using XCode 10 on a 64-bit Mac running MacOS version 10.13.6 and I was wondering how to fix the source code to make VertexHelper run on it. Thanks.

**Comment by jfahrenkrug** [comment]
@Ermiasmarino I've fixed it, should work now: https://github.com/jfahrenkrug/VertexHelper/pull/11

**Comment by Ermiasmarino** [comment]
Thanks a lot Johannes. It is working now perfectly. I love you. May The Almighty God bless you forever. Amen.

**Comment by jfahrenkrug** [comment]
@Ermiasmarino Thank you so much for your kind words, I'm happy it's working for you.

**Comment by Ermiasmarino** [comment]
You are most welcome Johannes :).
